
seata:
  enabled: true
  application-id: gulimall-ware-12000
  tx-service-group: my_test_tx_group
  #  config:
  #    type: nacos
  #    nacos:
  #      namespace:
  #      serverAddr: 59.110.137.100:8848
  #      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      server-addr: 59.110.137.100:8848
      namespace:

server:
  port: 12000

spring:

  #redis配置
  redis:
    host: 59.110.137.100
    port: 6379

  application:
    name: gulimall-ware-12000
  cloud:
    nacos:
      discovery:
        server-addr: 59.110.137.100:8848 #配置Nacos地址

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://59.110.137.100:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  jackson:
    date-format: yyyy-MM-dd #HH:mm:ss
#      initial-size: 10
#      max-active: 100
#      min-idle: 10
#      max-wait: 60000
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000


mybatisplus:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.project: debug
